.TH "bongo-manager" 1 "Bongo Project" "http://bongo-project.org/"
.SH "NAME" 
bongo-manager \(em Bongo Management Utility 
.SH "SYNOPSIS" 
.PP
.B bongo-manager
.RI [ options ]
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
.B bongo-manager
command. 
.PP 
.B bongo-manager
is a program to manage the Bongo server. 
.SH "OPTIONS" 
.PP 
A summary of options is included below. 
.TP
.BR \-h ", " \-\^\-help
Help. Display available commands.
.TP
.BR \-r ", " \-\^\-restart
Restart running Bongo agents.
.TP
.BR \-\^\-status
Report on running Bongo agents.
.TP
.BR \-s ", " \-\^\-stop
Terminate running Bongo agents.
.SH "SEE ALSO" 
.PP 
bongo-setup(1), bongo-admin(1) 
.SH "AUTHOR" 
.PP 
This manual page was originally written by Alex Hudson <home@alexhudson.com> for the
.B Debian
system (but may be used by others) and was updated by Jonny Lamb <jonnylamb@jonnylamb.com>.  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU  General Public License, Version 2, as published by the Free Software Foundation. 
