.TH "bongo-config" 1 "Bongo Project" "http://bongo-project.org/"
.SH NAME
bongo-config \- configures parts of the Bongo server
.SH SYNOPSIS
.B bongo-config
.RI [ options ]
.I COMMAND
.SH DESCRIPTION
.B bongo-config
installs the necessary configuration to the Bongo Store. It takes a
.I COMMAND
on execution to specify its action.
.SH OPTIONS
.TP
.BR \-v ", " \-\^\-verbose
Show verbose output.
.TP
.BR \-s ", " \-\^\-silent
Non-interactive mode.
.SH COMMANDS
.BI "user add " USER
Add a user to the system.
.TP
.BR "user list"
List the users on the system.
.TP
.BI "user password " USER
Set the password of
.I USER
.TP
.BR install
Do the initial Bongo install.
.TP
.BR crypto
Generate data needed for encryption.
.TP
.BR checkversion
Check whether a newer Bongo is available.
.TP
.BR tzcache
Regenerate cached timezone information.
.SH "AUTHOR"
This man page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
bongo-setup(1), bongo-admin(1)
