.TH "mdbtool" 1 "Bongo Project" "http://bongo-project.org/"
.SH NAME
mdbtool \- Manges the Bongo MDB agent
.SH SYNOPSIS
.B mdbtool
.RI [ options ]
.I COMMAND
.SH DESCRIPTION
.B mdbtool
manages the operation of the Bongo MDB agent. It takes a
.I COMMAND
on execution to specify its action.
.SH OPTIONS
.TP
.BR \-h ", " \-\^\-help
Show help message and exit.
.TP
.BI \-p " PASSWORD" "\fR,\fP \-\^\-password=" PASSWORD
Use password
.I PASSWORD
for authentication.
.TP
.BI \-u " USERNAME" "\fR,\fP \-\^\-username=" USERNAME
Use username
.I USERNAME
for authentication.
.SH "COMMANDS"
.TP
.BR getbasedn
.TP
.BI "getattrs " OBJECT " " ATTRNAME
.TP
.BI "getdnattrs " OBJECT " " ATTRNAME
.TP
.BI "addattr " OBJECT " " ATTRNAME " " VALUE
.TP
.BI "setattr " OBJECT " " ATTRNAME " " VALUE
.TP
.BI "addobject " OBJECT " " CLASS " \fR[attr1=value1 attr2=...]\fP"
.TP
.BI "delobject " OBJECT " \fR[\fP " true " \fR|\fP " false " \fR]\fP"
.TP
.BI "listobjects " OBJECT
.TP
.BI "setpassword " OBJECT " \fR[\fP " PASSWORD " \fR|\fP \-f " PWFILE " \fR]\fP"
.TP
.BI "verifypassword " OBJECT " " PASSWORD
.TP
.BI "isobject " OBJECT
.TP
.BI "defattr " ATTRNAME " " ASN1 " \fR[opt1=val1 opt2=...]\fP"
.TP
.BI "defclass " CLASSNAME " " ASN1 " \fR[opt1=val1 opt2=...]\fP"
.TP
.BI "defclassattr " CLASSNAME " " ATTRNAME
.TP
.BI "delattrdef " ATTRNAME
.TP
.BI "delclassdef " CLASSNAME
.TP
.BI "grantobj " OBJECT " " TRUSTEE " \fR[opt=val1 opt2=...]\fP"
.TP
.BI "grantattr " OBJECT " " ATTRNAME " " TRUSTEE " \fR[opt1=val1 opt2=...]\fP"
.TP
.BI "gethostipaddr "
.SH "AUTHOR"
This man page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
bongo-setup(1), bongo-admin(1)
