#!/usr/bin/perl

# Run ls | ./write-makefile-am.pl > Bongo.rules

print "# This file is autogenerated.\n";
print "# Run ls | ./write-makefile-am.pl > Bongo.rules to regenerate.\n\n";
print "noinst_HEADERS += \\\n";

while (<>) {
    chomp;
    if (/\.h$/) {
	print "\tsrc/libs/streamio/codec/$_ \\\n";
    }
}
print "\t\$(NULL)\n"
