#define NMAP_AFLG_HELP "AFLG <Sequence Number> <Flags> - Add message Flags to designated message.\r\n"
#define NMAP_AINFO_HELP "AINFO [<Sequence Number>] - Returns information for designated message.\r\n"
#define NMAP_AUTH_HELP "AUTH <Hash> - Authenticates un-trusted hosts using an MD5 hash of the NMAP password.\r\n"
#define NMAP_CAPA_HELP "CAPA - List the NMAP version and extensions.\r\n"
#define NMAP_CONF_HELP "CONF - ???\r\n"
#define NMAP_DCOPY_HELP "DCOPY"
#define NMAP_DCREA_HELP "DCREA"
#define NMAP_DFLG_HELP "DFLG <Sequence Number> <Flags> - Remove Flags from the designated message.\r\n"
#define NMAP_DGUID_HELP "DGUID [<count>] - Returns 1, or count, of NMAP globally unique identifiers; not to exceed 65,535.\r\n"
#define NMAP_DINFO_HELP "DINFO [<NMAP GUID>] - Returns information on the optionally designated document guid; otherwise, returns information on all documents in the user's document store.\r\n"
#define NMAP_DINSET_HELP "DINSET [*(<NMAP GUID>)]"
#define NMAP_DLIST_HELP "DLIST *(<NMAP GUID>)"
#define NMAP_DMOVE_HELP "DMOVE"
#define NMAP_DPGET_HELP "DPGET"
#define NMAP_DPSET_HELP "DPSET"
#define NMAP_DPURG_HELP "DPURG"
#define NMAP_DREAD_HELP "DREAD *(<NMAP GUID>)"
#define NMAP_DREPL_HELP "DREPL <guid> <revision> <length> [I<index>]"
#define NMAP_DSTOR_HELP "DSTOR <resource> <type> <length> [G<guid> <source revision>] [D<date>] [M<modified>]\r\n"
#define NMAP_DUNFO_HELP "DUNFO"
#define NMAP_DUNSET_HELP "DUNSET [*(<NMAP GUID>)]"
#define NMAP_FLAG_HELP "FLAG - Sets parameters for the current NMAP connection.\r\n"
#define NMAP_HELP_HELP "HELP [Command] - Without an argument, lists all NMAP Commands, otherwise lists basic description of Command\r\n"
#define NMAP_NOOP_HELP "NOOP - Does nothing.  This is useful for polling for OOB messages.\r\n"
#define NMAP_OPER_HELP "OPER - ???"
#define NMAP_PRINC_HELP "PRINC {USER | EMAIL} <principal> - Identify as the designated principal.\r\n"
#define NMAP_PASS_HELP "PASS {SYS | <USER <Username>} <Password> - Authenticate as NMAP or Username with cleartext Password.\r\n"
#define NMAP_QUIT_HELP "QUIT - Closes the client's NMAP connection.\r\n"
#define NMAP_USER_HELP "USER <Username> - Selects the account for Username.\r\n"
#define NMAP_MANAGE_HELP "MANAGE - Gives a site manager rights to use the USER command.\r\n"
#define NMAP_VRFY_HELP "VRFY <Username> - Verify existence of Username.\r\n"

