
set(PACKAGE CMAKE_PROJECT_NAME)

set(LINUX TRUE)

if(HAVE_TIME_H)
	set(HAVE_NANOSLEEP 1)
endif(HAVE_TIME_H)

set(_BONGO_XPL_BIG_ENDIAN FALSE)
set(_BONGO_XPL_LITTLE_ENDIAN TRUE)
set(_BONGO_HAVE_DLFCN_H TRUE)


set(BONGO_BUILD_BRANCH "trunk")
set(BONGO_BUILD_VSTR "r")
set(BONGO_BUILD_VER "10")
